name: Tests Workflow

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test --ci
        env:
          CI: true
          NEXT_PUBLIC_SANITY_API_VERSION: ${{ github.env.NEXT_PUBLIC_SANITY_API_VERSION }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ github.env.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ github.env.NEXT_PUBLIC_SANITY_DATASET }}
          projectId: $NEXTPUBLIC_SANITY_PROJECT_ID
          dataset: $NEXTPUBLIC_SANITY_DATASET
          apiVersion: $NEXTPUBLIC_SANITY_API_VERSION
